/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.umbraldiu;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.highgui.HighGui;
import org.opencv.imgcodecs.Imgcodecs;

/**
 *
 * @author Sara
 */
public class Frame extends javax.swing.JFrame {

    /** Creates new form Frame */
    JFileChooser fc = new JFileChooser();
    FileNameExtensionFilter filtro = null;
    Mat img = null;
    Mat imgu = null;
        
    public Frame() {
        nu.pattern.OpenCV.loadShared();
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageC = new com.mycompany.umbraldiu.CanvasImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mBar = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mOpen = new javax.swing.JMenuItem();
        mSave = new javax.swing.JMenuItem();
        mTreshold = new javax.swing.JMenu();
        mSetTreshold = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        mAbout = new javax.swing.JMenuItem();
        mExit = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout imageCLayout = new javax.swing.GroupLayout(imageC);
        imageC.setLayout(imageCLayout);
        imageCLayout.setHorizontalGroup(
            imageCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        imageCLayout.setVerticalGroup(
            imageCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        jLabel1.setText("Alejandro García Sosa");

        jLabel2.setText("Santiago Higuita Ardila");

        mFile.setMnemonic('f');
        mFile.setText("File");

        mOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mOpen.setText("Open File");
        mOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOpenActionPerformed(evt);
            }
        });
        mFile.add(mOpen);

        mSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mSave.setText("Save File");
        mSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveActionPerformed(evt);
            }
        });
        mFile.add(mSave);

        mBar.add(mFile);

        mTreshold.setMnemonic('e');
        mTreshold.setText("Edit");

        mSetTreshold.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mSetTreshold.setText("Set Treshold");
        mSetTreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSetTresholdActionPerformed(evt);
            }
        });
        mTreshold.add(mSetTreshold);

        mBar.add(mTreshold);

        mHelp.setMnemonic('h');
        mHelp.setText("Help");

        mAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mAbout.setText("About");
        mAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAboutActionPerformed(evt);
            }
        });
        mHelp.add(mAbout);

        mBar.add(mHelp);

        mExit.setMnemonic('x');
        mExit.setText("Exit");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        mExit.add(Exit);

        mBar.add(mExit);

        setJMenuBar(mBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int ex = JOptionPane.showConfirmDialog(this, "¿Desea cerrar la aplicación?", "EXIT", JOptionPane.YES_NO_OPTION);
        if(ex == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void mSetTresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSetTresholdActionPerformed
        // TODO add your handling code here:
        if(img == null){
            JOptionPane.showMessageDialog(this, "No ha seleccionado imagen", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                int treshold = Integer.parseInt(JOptionPane.showInputDialog(this,"Introduzca un número entero"));
                imgu = Umbralizador.umbralizar(img, treshold);
                imageC.setImage((BufferedImage) HighGui.toBufferedImage(imgu));
            }catch(NumberFormatException E){
                JOptionPane.showMessageDialog(this, "Introduzca un número entero", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mSetTresholdActionPerformed

    private void mOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOpenActionPerformed
        filtro = new FileNameExtensionFilter("Imagen", "jpg", "png");
        fc.setFileFilter(filtro);
        int res = fc.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            File fichero = fc.getSelectedFile();
            img = Imgcodecs.imread(fichero.getAbsolutePath());
            imageC.setImage((BufferedImage) HighGui.toBufferedImage(img));
            pack();
        }
    }//GEN-LAST:event_mOpenActionPerformed

    private void mSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSaveActionPerformed
        int res = fc.showSaveDialog(null);
        if(img == null){
            JOptionPane.showMessageDialog(this, "No ha seleccionado imagen", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            if(res == JFileChooser.APPROVE_OPTION){
                if(imgu == null){
                    int resu = JOptionPane.showConfirmDialog(this, "La imagen no se ha modificado. ¿Guardar de todos modos?", "IMAGEN NO MODIFICADA", JOptionPane.YES_NO_OPTION);
                    if(resu == JOptionPane.YES_OPTION){
                        File fichero = fc.getSelectedFile();
                        Imgcodecs.imwrite(fichero.getAbsolutePath(),img);
                    }
                }else{
                    int res2 = JOptionPane.showConfirmDialog(this, "¿Quiere guardar el archivo?", "GUARDAR IMAGEN", JOptionPane.YES_NO_OPTION);
                    if(res2 == JOptionPane.YES_OPTION){
                        File fichero = fc.getSelectedFile();
                        Imgcodecs.imwrite(fichero.getAbsolutePath(),imgu);
                    }
                }
            }
        }
    }//GEN-LAST:event_mSaveActionPerformed

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
    }//GEN-LAST:event_mExitActionPerformed

    private void mAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAboutActionPerformed
        String help[] = {"Elegir Imagen", "Guardar imagen", "Elegir umbral", "Salir de la aplicación", "Lista de atajos", "Sobre nosotros"};
        JComboBox jHelp = new JComboBox(help);
        boolean lo = true;
        int res;
        while(lo){
            res = JOptionPane.showConfirmDialog( null, jHelp, "Acerca de", JOptionPane.OK_CANCEL_OPTION);
            if(res == JOptionPane.OK_OPTION){
                switch(jHelp.getSelectedIndex()){
                case 0: JOptionPane.showMessageDialog(this, "Para elegir una imagen, use la opción 'Open Image' del menú 'File'.\nPuedes cambiar de imagen en cualquier momento, y la aplicación se ajustará automáticamente a su tamaño.");
                    break;
                case 1: JOptionPane.showMessageDialog(this, "Para guardar una imagen umbralizada, use la opción 'Save Image' del menú 'File'.");
                    break;
                case 2: JOptionPane.showMessageDialog(this, "Para cambiar el umbral, use el opción 'Set Treshold' del menú 'Edit'.\nPuedes cambiar el umbral tantas veces como quieras.");
                    break;
                case 3: JOptionPane.showMessageDialog(this, "Para salir, use la pción 'Exit' del menú 'Exit'.\nUsar la 'X' está desactivado");
                    break;
                case 4: JOptionPane.showMessageDialog(this, "Abrir imágen: 'Ctrl+O'\nGuardar imágen: 'Ctrl+S'\nModificar umbral: 'Ctrl+E'\nAbrir la ayuda: 'Ctrl+H'\nSalir de la aplicación: 'Ctrl+Shift+E'");
                    break;
                case 5: JOptionPane.showMessageDialog(this, "Umbralizador de imágenes marca ACME\nVersión 1.0.1\n\nHecho por:\nAlejandro García Sosa\nSantiago Higuita Ardila");
                    break;
                default: JOptionPane.showMessageDialog(this, "Ayuda no disponible\nDicho sea de paso, ¿Cómo es posible que estés viendo esto?", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                lo = false;
            }
            
        }
    }//GEN-LAST:event_mAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private com.mycompany.umbraldiu.CanvasImage imageC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem mAbout;
    private javax.swing.JMenuBar mBar;
    private javax.swing.JMenu mExit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuItem mOpen;
    private javax.swing.JMenuItem mSave;
    private javax.swing.JMenuItem mSetTreshold;
    private javax.swing.JMenu mTreshold;
    // End of variables declaration//GEN-END:variables

}
